### ISSUE TITLE
Try to mirror the actions from the vid

### ISSUE THREAD

**Issue by CPatSweco** [iTwin/Course_1-Smart-House-Sample#15]
Hi, I'm trying to reproduce the steps from the video but I get stuck on this part?

![image](https://user-images.githubusercontent.com/97593583/184362246-c7960cc7-163d-4c2a-8507-19353ba8a3de.png)
 
And I copy this to my App.tsx and get this error message?

![Smrt_02](https://user-images.githubusercontent.com/97593583/184362856-4572cba8-f65d-4d70-8632-727e7aa6d289.JPG)

The Text "WHERE CodeValue IN" looks quite diffrent as in the video

**Comment by aruniverse** [comment]
You need to use the backtick character when writing [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
```
`
```
